version: 2

# Templates
defaults: &defaults # We use the machine executor, i.e. a VM, not a container
  machine:
    # Cache docker layers so that we strongly speed up this job execution
    # This cache will be available to future jobs (although because jobs run
    # in parallel, CircleCI does not guarantee that a given job will see a
    # specific version of the cache. See documentation for details)
    docker_layer_caching: true

  working_directory: ~/fun

build_steps: &build_steps
  steps:
    # Checkout openedx-docker sources
    - checkout

    # Skip release build & testing if changes are not targeting it
    - run:
        name: Check if changes are targeting the current release
        command: bin/ci checkpoint

    # Install a recent docker-compose release
    - run:
        name: Upgrade docker-compose
        command: |
          curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose

    # Production image build. It will be tagged as edxapp:latest
    - run:
        name: Build production image
        command: |
          source $(bin/ci activate_path)
          make build

    # Bootstrap
    - run:
        name: Bootstrap the app
        command: |
          source $(bin/ci activate_path)
          make dev-assets
          make migrate

    # Check that the production build starts
    - run:
        name: Start development server
        command: |
          source $(bin/ci activate_path)
          make dev

jobs:
  # Git jobs
  # Check that the git history is clean and complies with our expectations
  lint-git:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/fun
    steps:
      - checkout
      # Make sure the changes don't add a "print" statement to the code base.
      # We should exclude the ".circleci" folder from the search as the very command that checks
      # the absence of "print" is including a "print(" itself.
      - run:
          name: enforce absence of print statements in code
          command: |
            ! git diff origin/master..HEAD -- . ':(exclude).circleci' | grep "print("
      - run:
          name: Check absence of fixup commits
          command: |
            ! git log | grep 'fixup!'
      - run:
          name: Install gitlint
          command: |
            pip install --user gitlint
      - run:
          name: lint commit messages added to master
          command: |
            ~/.local/bin/gitlint --commits origin/master..HEAD

  # Check that the CHANGELOG has been updated in the current branch
  check-changelog:
    docker:
      - image: circleci/buildpack-deps:stretch-scm
    working_directory: ~/fun
    steps:
      - checkout
      - run:
          name: Check that the CHANGELOG has been modified in the current branch
          command: |
            git whatchanged --name-only --pretty="" origin..HEAD | grep CHANGELOG

  # Check that the CHANGELOG max line length does not exceed 80 characters
  lint-changelog:
    docker:
      - image: debian:stretch
    working_directory: ~/fun
    steps:
      - checkout
      - run:
          name: Check CHANGELOG max line length
          command: |
            # Get the longuest line width (ignoring release links)
            test $(cat CHANGELOG.md | grep -Ev "^\[.*\]: https://github.com/openfun" | wc -L) -le 80

  # Build jobs
  #
  # Note that the job name should match the EDXEC_RELEASE value
  master-bare:
    <<: [*defaults, *build_steps]

  dogwood.3-fun:
    <<: [*defaults, *build_steps]

  ironwood.2-bare:
    <<: [*defaults, *build_steps]

  # Hub job
  hub:
    <<: *defaults

    steps:
      - checkout

      # Install a recent docker-compose release
      - run:
          name: Upgrade docker-compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      # Thanks to docker layer caching, rebuilding the image should be blazing
      # fast!
      - run:
          name: Rebuild production image
          command: |
            source $(bin/ci activate_path)
            make build

      # Tag images with our DockerHub namespace (fundocker/), and list images to
      # check that they have been properly tagged.
      - run:
          name: Tag production image
          command: |
            source $(bin/ci activate_path)
            docker tag edxec:${EDXEC_DOCKER_TAG} fundocker/edxec:${CIRCLE_TAG}
            docker images fundocker/edxec:${CIRCLE_TAG}

      # Login to DockerHub with encrypted credentials stored as secret
      # environment variables (set in CircleCI project settings)
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      # Publish the production image to DockerHub
      - run:
          name: Publish production image
          command: |
            docker push fundocker/edxec:${CIRCLE_TAG}

workflows:
  version: 2

  ecommerce:
    jobs:
      # Quality
      - lint-git:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - check-changelog:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - lint-changelog:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/

      # Build jobs
      - master-bare:
          filters:
            tags:
              ignore: /.*/
      - dogwood.3-fun:
          filters:
            tags:
              ignore: /.*/
      - ironwood.2-bare:
          filters:
            tags:
              ignore: /.*/

      # We are pushing to Docker only images that are the result of a tag respecting the pattern:
      #    **{branch-name}-x.y.z**
      #
      # Where branch-name is of the form: **{edx-version}[-{fork-name}]**
      #   - **edx-version:** name of the upstream `edx-platform` version (e.g. ginkgo.1),
      #   - **fork-name:** name of the specific project fork, if any (e.g. funwb).
      #
      # Some valid examples:
      #   - dogwood.3-1.0.3
      #   - dogwood.2-funmooc-17.6.1
      #   - eucalyptus-funwb-2.3.19
      - hub:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[a-z0-9.]*-?[a-z]*-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
